Repository nextcloud/user_external, pull requests merged in 2019-03, with the labels that each got.

#39 add PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: 3. to review, enhancement

#48 add 'User External App version' to issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: enhancement

#49 Do IMAP auth over direct socket connection
  README.md
  lib/imap.php
  lib/imap/imap_rcube.php
Labels: 3. to review, bug, enhancement

#53 📖 DOC: sslmode is a string too && add possible values for sslmode
  README.md
Labels: 3. to review, bug, high

#55 change documentation link to github readme
  appinfo/info.xml
Labels: 3. to review, enhancement

#54 basic authentication now follows redirects!
  lib/basicauth.php
Labels: 3. to review, bug, enhancement

#37 Add Prosody XMPP MySQL DB authentication
  README.md
  appinfo/app.php
  appinfo/info.xml
  lib/xmpp.php
Labels: 3. to review, enhancement

#50 🐛 FIX: pr template needs to be in .github/ directly
  .github/pull_request_template.md
Labels: 3. to review
