Repository nextcloud/user_external, pull requests merged in 2019-05, with the labels that each got.

#75 Cleanly close imap connection
  lib/imap.php
Labels: 4. to release, bug

#63 add basic auth configuration security warning
  README.md
Labels: 3. to review, high, security

#79 SSH password authentication
  README.md
  appinfo/app.php
  lib/ssh.php
Labels: 3. to review, enhancement
