Repository nextcloud/user_external, pull requests merged in 2019-01, with the labels that each got.

#26 prepare to release in appstore
  appinfo/info.xml
Labels: 3. to review

#30 occ check-code compliance
  appinfo/info.xml
  lib/base.php
  lib/ftp.php
  lib/imap.php
  lib/smb.php
  lib/webdavauth.php
Labels: 3. to review, high

#34 Implements error handling for imap errors #11
  lib/imap.php
Labels: 3. to review, enhancement
