Repository nextcloud/user_external, pull requests merged in 2019-02, with the labels that each got.

#38 Add authentication against basic auth
  README.md
  appinfo/app.php
  lib/basicauth.php
  tests/basic_auth.php
  tests/config.php
Labels: 3. to review, enhancement

#31 .travis.yml and .drone.yml to make automatic CI tests work
  .drone.yml
  .travis.yml
  tests/bootstrap.php
  tests/configuration.xml
Labels: 3. to review, enhancement, help wanted

#41 add Makefile to simplify releases
  .gitignore
  Makefile
Labels: 3. to review, enhancement

#42 🚀 RELEASE: v0.5.1
  appinfo/info.xml
Labels: 3. to review

#43 fix broken readme links
  README.md
Labels: 3. to review, bug
