Repository nextcloud/user_external, pull requests merged in 2019-06, with the labels that each got.

#65 optional imap groups via domain & make domain striping optional
  README.md
  lib/base.php
  lib/imap.php
Labels: 3. to review, enhancement

#82 Address issue #58
  lib/basicauth.php
Labels: 3. to review, enhancement, security

#84 update description
  README.md
  appinfo/info.xml
Labels: 3. to review, enhancement

#92 🐛 FIX: travis mysql and postgresql build
  .travis.yml
Labels: bug

#83 Fix Issue #56: Undefined Indices in Logs
  lib/imap.php
  lib/imap/imap_rcube.changes2upstream
  lib/imap/imap_rcube.php
Labels: 3. to review, bug

#91 📦 NEW: support counting of total user_external users
  lib/base.php
Labels: 3. to review, bug, enhancement

#90 🐛 FIX: variable groups not set in all cases
  lib/imap.php
Labels: 3. to review, bug

#94 🚀 RELEASE: v0.6.4
  Makefile
  appinfo/info.xml
Labels: 3. to review
