Repository nextcloud/user_external, pull requests merged in 2024-07, with the labels that each got.

#255 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
Labels: 3. to review, dependencies, automated

#249 🐛 FIX: wrong user count
  lib/Base.php
Labels: bug, 3. to review

#256 🚀 RELEASE: v3.4.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
