Repository nextcloud/user_external, pull requests merged in 2024-04, with the labels that each got.

#248 🚀 RELEASE: v3.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#242 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
Labels: 3. to review, dependencies, automated

#221 Update README.md, add warning about fail2ban-like tools
  README.md
Labels: 4. to release, documentation

#251 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies
